kind: CronJob
apiVersion: batch/v1
metadata:
  name: min-backup
  namespace: nginx

spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          name: min-backup
          labels:
            app: min-backup
        spec:
          containers:
          - name: cron-job
            image: busybox:latest
            command: ["sh", "-c", "echo Hello Dosto! backup started && mkdir -p /backups && mkdir -p /demo-data && sleep 10s"]
            volumeMounts:
            - name: data-volume
              mountPath: /demo-data
            - name: backup-volume
              mountPath: /backups
          restartPolicy: OnFailure
          volumes:
          - name: data-volume
            hostPath:
              path: /demo-data
              type: DirectoryOrCreate
          - name: backup-volume
            hostPath:
              path: /backups
              type: DirectoryOrCreate
