kind: Deployment
apiVersion: apps/v1
metadata:
  name: notes-app-deploy
  labels: 
    app: notes-app
  namespace: notes-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-app
  
  template:
    metadata:
      labels:
        app: notes-app
    spec:
      containers:
        - name: notes-appnx
          image: rahuldubey1/notes-app-k8s
          ports:
            - containerPort: 8000
